
name: Build and Test Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag pdf-toolkit:latest

      - name: Run container test
        run: |
          docker run -d -p 8000:8000 --name pdf-toolkit pdf-toolkit:latest
          sleep 10
          curl -f http://localhost:8000 || (docker logs pdf-toolkit && exit 1)